# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe7a822ddd15140474906fdc11020c709c23355864778b4357158a423d7fdd4bcc85ab204b4137cec6aaf01fef2d7ddff206fc5b224a842be135449174e4447e

test:
  secret_key_base: f82e7eaeb945ec047d0d38da90fc1d202a93f333eac7edc9a3f78a0e251f19aa8f34ec9eacf90b3124883a49058b929f8a449ea3cc5780f398cf3c51f1b40019

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
